// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rpbasjdudykdmktxusuy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJwYmFzamR1ZHlrZG1rdHh1c3V5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyMTMxMzgsImV4cCI6MjA3Mzc4OTEzOH0.TiT-92JHQjcAEzc_flBOpr8s0ksKuAVbhhevn7MXs04";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});